version: '2'
services:
  web:
    build: ./app/
    command: npm run start
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx/
    ports:
      - "80:80"